### ISSUE TITLE
Negative infravision leads to infinite infravision

### ISSUE THREAD

**Issue by mangband** [mangband/mangband#1002]
Issue raised by flambard

Similar to #454, 
> Thorbear: would seem infra-vision effectively wraps around backwards when below 0
> Thorbear: making cursed amulets of infravision into amulets of infinite infravision
> ...
> Thorbear: My best bet on why it happens is in monster2.c
> Thorbear: if (m_ptr->cdis <= (byte)(p_ptr->see_infra))

**Comment by evileye-uk** [comment]
Infravision should not become negative - it's displayed as negative even though the effect should just be that it is zero. The cast to byte is still wrong.

**Comment by flambard-took** [comment]
Fixed in both master and stable, closing it.
