### ISSUE TITLE
Remembered map not being reset correctly on login/logout

### ISSUE THREAD

**Issue by mangband** [mangband/mangband#1005]
Issue raised by flambard

"Uhm, ironman seems to "remember" the tiles even after the map has changed. Granting the player a good view of the fresh level when logging in.

If you explore a level with Character_One, then log out, wait for the level-reset-timer to run out, then enter the level with Character_Two to trigger level generation, log out, then log back in with Character_One.

Character_One will then have most of the map visible (even the walls you would normally not see)."

reported by Thorbear. Probably different in trunk.

**Comment by flambard-took** [comment]
Porting this from PWMangband right now (man, the code does look much cleaner!), and noticed you're not setting quit_turn anywhere? Just a heads up.
