### ISSUE TITLE
Unavoidable instagib when logging back (ironman)

### ISSUE THREAD

**Issue by mangband** [mangband/mangband#1014]
Issue raised by powerwyrm

While this is perfectly understandable on normal servers (you should recall and save in town), being instakilled because you reconnect in a room full of hounds that all breathe on you before you have the chance of doing anything when playing ironman is not acceptable. There should be a way to connect safely, or at least a chance to escape the death sentence.

Note that is tricky to fix without being abusable. Leave floors static for ironman (TomeNET do that)? Give a staff of teleportation at birth? Banish monsters in a small area when logging back?

**Comment by flambard-took** [comment]
I'm thinking giving players bullet time on re-login is the best way to go. (As per Warrior's comment)

However, I don't want to mess with the time bubble code right now, so for a lesser, worse solution, I'm going to simply give players 2 turns of GoI. (Why 2? 1 passes-by too quickly, by my subjective measurements). I don't think there's any way to *sensibly* abuse this.
