### ISSUE TITLE
Build failure on FreeBSD amd64

### ISSUE THREAD

**Issue by mangband** [mangband/mangband#1020]
Issue raised by flambard

FreeBSD notifies us, that it's automatic build of mangband failed.

Log URL:        http://beefy2.isc.freebsd.org/bulk/head-amd64-default/2013-09-12_01h37m09s/logs/mangband-1.1.2.log

**Comment by flambard-took** [comment]
New plan: drop freebsd port from our repository. It lives in it's own repo with people patching it on their own. It's unproductive to try to keep track of it here.
