### ISSUE TITLE
Vegetables don't list their nutrition values

### ISSUE THREAD

**Issue by mangband** [mangband/mangband#1022]
Issue raised by flambard

This should be rather easy to fix.

All V items, that DO nutrition you, have their values listed in the description.

Reported by Gaël, https://mangband.org/forum/viewtopic.php?f=13&t=2090

**Comment by flambard-took** [comment]
And in case some is wondering what happened next,
V309 - same bug
V312 - descriptions no longer provide nourishment spoilers, values have changed
V404 - file format changed a bit, but values are similar to V312
