### ISSUE TITLE
Write init scripts for all popular daemon supervisors

### ISSUE THREAD

**Issue by flambard-took** [mangband/mangband#1054]
According to the latest best practices, daemon programs **should not** use `fork()` to start child processes (shell capability `&` is considered enough), nor write logs (`stdout` and `stderr` are good enough).

It is now considered to be daemon supervisor's job to actually fork and redirect those streams to proper log files. Which is a relief (and makes total sense).

But we lack those scripts.

I'm thinking
- [x] initV .sh (classic init.d stuff)
- [x] OpenRC .sh (gentoo)
- [x] rc.d .sh (FreeBSD)
- [x] upstart .conf (olden ubuntu)
- [x] systemd unit (everything else)

We don't have to make those _perfect_, as distro packagers will have to rewrite them anyway. However it'll ease their pain _AND_ it'll allow rouge users to run the mangband server much more easily.

Please use the `dist/init/SYSTEM` directory to put the scripts into, i.e. `dist/init/upstart/mangband.conf`.

**Comment by flambard-took** [comment]
Since systemd is the least understood system out of that bunch, I'm leaving this here:

```
[Unit]
Description=service_description
After=network.target

[Service]
ExecStart=path_to_executable
Type=forking
PIDFile=path_to_pidfile

[Install]
WantedBy=default.target
```

Note: `Type=forking` means the daemon calls `fork()`, we should use some other value (`simple`?).

Note: also have to figure out how to write logs to appropriate locations.

**Comment by grking** [comment]
Here's what's running on morgoth. Works fine with:

```
systemctl start mangband
systemctl stop mangband
systemctl status mangband
etc
```

Restarts on process failure.  

```[Unit]
Description=MAngband Service
Wants=network-online.target
After=network-online.target
[Service]
User=mangband
Group=mangband
WorkingDirectory=/home/mangband/game-server
Type=simple
ExecStart=/home/mangband/game-server/mangband
ExecStop=/bin/kill -2 $MAINPID
ExecStop=/bin/sleep 1
ExecStop=/bin/kill -2 $MAINPID
ExecStop=/bin/sleep 1
ExecStop=/bin/kill -2 $MAINPID
ExecStop=/bin/sleep 1
ExecStop=/bin/kill -2 $MAINPID
ExecStop=/bin/sleep 1
ExecStop=/bin/kill -2 $MAINPID
ExecStop=/bin/sleep 1
KillMode=process
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
```
