### ISSUE TITLE
Client INI file uses wrong defaults for window size

### ISSUE THREAD

**Issue by billsey** [mangband/mangband#1126]
They should all be 80x24. The master version instead uses 79x24, 58x12 and 59x24 for some windows.

**Comment by flambard-took** [comment]
Sorry, df7262e16655d77bc6136cfe7f4b9e8496e0665c was meant to ref #1128, not this ticket.

**Comment by flambard-took** [comment]
Sorry, 7613914be9b928daa73aba4e65e21f8b5587c5a3 was also meant for #1128, not this ticket.
