### ISSUE TITLE
Alpha-test version 1.5.0

### ISSUE THREAD

**Issue by flambard-took** [mangband/mangband#1130]

**Comment by flambard-took** [comment]
As decided, this is now called version 1.5.

**Comment by billsey** [comment]
I'm not seeing a 1.5 branch. Is this 1.4 or develop?

Get Outlook for Android<https://aka.ms/ghei36>




On Thu, Jan 31, 2019 at 10:18 AM -0800, "flambard-took" <notifications@github.com<mailto:notifications@github.com>> wrote:


As decided, this is now called version 1.5.

**Comment by flambard-took** [comment]
This comment concerned `master` branch (previously known as 1.2.0, also known as "old trunk from svn").

Nice to see you :)
