### ISSUE TITLE
Account creation error on website

### ISSUE THREAD

**Issue by shmup** [mangband/mangband#1136]
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'rand_seed_last_update' for key 'PRIMARY'' in /home/flambard/local-web/passwd/mysql.class.php:45 Stack trace: #0 /home/flambard/local-web/passwd/mysql.class.php(45): PDOStatement->execute(NULL) #1 /home/flambard/local-web/passwd/plugin.phpbb3.php(46): YQL->exec('INSERT INTO php...') #2 /home/flambard/local-web/passwd/plugin.phpbb3.php(53): fakedb->_flush() #3 /var/www/html/forum/includes/functions_user.php(250): fakedb->sql_query('INSERT INTO USE...') #4 /home/flambard/local-web/passwd/plugin.signup.php(142): user_add(Array) #5 [internal function]: do_guest_signup('NotActualAccount', 'DUDE_PLAIN_TEXT?', 'DUDE_PLAIN_TEXT?') #6 /home/flambard/local-web/passwd/act.php(35): call_user_func_array('do_guest_signup', Array) #7 /home/flambard/local-web/passwd/index.php(37): include('/home/flambard/...') #8 {main} thrown in /home/flambard/local-web/passwd/mysql.class.php on line 45

Don't show this to the public. Handle better.

**Comment by grking** [comment]
The whole website has been replaced, this is not relevant.
