### ISSUE TITLE
MAngband 1.1.3 compilation error

### ISSUE THREAD

**Issue by dchmelik** [mangband/mangband#1137]
On Slackware GNU/Linux, I get the following compilation error, which seems to be with SDL: [https://gist.github.com/dchmelik/1157ecd065e98552c7f8bc85f981b81d](url) . I have SDL installed and use it with other software, so it wouldn't be a problem with SDL itself.

**Comment by evileye-uk** [comment]
Kmmb km ju. Ii

**Comment by evileye-uk** [comment]
Mmk

**Comment by evileye-uk** [comment]
Ok 0mlis k

**Comment by Thorbear** [comment]
You ok, @evileye-uk ?

**Comment by Thorbear** [comment]
Updated gist: https://gist.github.com/Thorbear/e69840b9c52f44784d8052cf557b6721

**Comment by evileye-uk** [comment]
Hmm. Thanks for the heads up.

**Comment by flambard-took** [comment]
AFAIK, newer (?) versions of gcc are rightfully not happy about those externs being mixed up. I have definitely patched over this during some builds, could swear that was in the tree :( Probably thinking about the master branch.

Sorry, don't have access to a proper dev.environment right now, but I'll try to come up with something.

**Comment by Morgoth-Lopper** [comment]
Are we down for maintenance?
Web site Mangband.org - Unable to establish a database connection.

Mangband Client - No servers show up on the list.
