### ISSUE TITLE
Server down.

### ISSUE THREAD

**Issue by Qualta** [mangband/mangband#1138]
Hi i have played mang for many years now and i am just wondering if there is anyone still left looking after it or if this time the main server has gone for ever this time? I have loved the game and all the hard work you guys put into to it over the years and if i had any coding knowledge i would offer my services.
Hopefuly this is just a temporary issue but it would be nice to know either way.

Thanks for your time.

**Comment by flambard-took** [comment]
Thanks for the heads-up, and good call making a ticket here (e-mail notifications!).

(Answering your other question, the team is largely dispersed, but we do still consider the project alive.)

**Comment by grking** [comment]
We are always watching, even if from afar these days...

- Jug

**Comment by Morgoth-Lopper** [comment]
thanks and sorry I have not been on this gmail account for a while

**Comment by Qualta** [comment]
Hi guys mang is down again just a heads up.

cheers

________________________________
