### ISSUE TITLE
looking in /usr/share/games for what's in /var/games

### ISSUE THREAD

**Issue by wxl** [mangband/mangband#1140]
Installing the 1.1.3 .deb on Ubuntu (Trusty) results in the server failing to start because it can't find `.lib/edit/limits.txt`. It is installed in `/var/games/mangband/edit/limits.txt` and indeed the `/var/games/mangband` folder includes all the files required by the server. I happened to stumble upon a [packaged version][1] which includes a file list different than the one in the .deb. Instead, everything appears to be in `/usr/share/games/mangband/lib`. I solved this by adding the `mangband` folder to `/usr/share/games` and symlinking `lib` to `/var/games/mangband` but it's an oddity none the less. I can't imagine this is something unique to Ubuntu (i.e. that Debian uses `/var/games` and Ubuntu strangely uses `/usr/share/games`), but… 🤷‍♂️ 

[1]: https://ubuntu.pkgs.org/16.04/getdeb-games-amd64/mangband_1.1.3-1~getdeb2_amd64.deb.html

**Comment by flambard-took** [comment]
For this to have any effect, we have to re-package and re-release all the .deb files :( I don't believe it's happening any time soon.

Thank you!
