### ISSUE TITLE
Windows client assume write access

### ISSUE THREAD

**Issue by grking** [mangband/mangband#1141]
The Windows client assumes it can write to the Program Files, which in all likelihood, in can't in recent versions of Windows.

**Comment by billsey** [comment]
At first glance we only need to do a Windows specific section in init_file_paths() and the rest falls into place.

**Comment by grking** [comment]
I was thinking specifically of %APPDATA%.

We could handle this entirely in the installer, without even any code changes. The Windows installer system installs the entire application in %APPDATA% if it's installed for "Current User Only" rather than "All Users".

**Comment by grking** [comment]
Replaced with #1152
