### ISSUE TITLE
Windows chat crash

### ISSUE THREAD

**Issue by grking** [mangband/mangband#1142]
It's been reported by a few players that in Windows 10 the client crashes instantly when trying to chat.

**Comment by evileye-uk** [comment]
Easy to reproduce this. Fixing it.

**Comment by grking** [comment]
The windows client uses API calls to do things like get a pointer to the window handler function.  It uses the 32bit versions of these API calls.  When compiled with a 32bit compiler but run on 64bit windows, these APi calls return 64bit pointers, which the 32bit windows client can't handle, resulting in segfault.

Fixed automagically no doubt by compiling a 64bit windows client, but that client won't run on 32bit Windows.  Which, oddly, is still a thing even with Windows 10.
