### ISSUE TITLE
Password shows up on login if saved in .ini file

### ISSUE THREAD

**Issue by igroglaz** [mangband/mangband#1144]
1) I added login/password in .INI file
2) when I enter the game and push 'Enter' key twice - at second push my password 'flashes' and appears to bee seen on a second.. after this it's covered with *****

It's pretty crucial issue because I make video stream and could flash my password accidentally :(

**Comment by evileye-uk** [comment]
PR https://github.com/mangband/mangband/pull/1146 addresses this in 1.1.4

**Comment by grking** [comment]
Fixed in `develop`
