### ISSUE TITLE
Inventory opening by default on some commands

### ISSUE THREAD

**Issue by grking** [mangband/mangband#1145]
In Vanilla, if you don't have a separate inventory window, some commands automatically display the inventory.  e.g. "drop" (d).  

This is a useful usability feature.

Noted by tangar.

**Comment by igroglaz** [comment]
To give more detailed explanation:

The idea is to show '*' (all items) automatically after each command (like 'r', 'w', 'd' & etc); for example, when I push 'd' (drop) - then to see list of items I got manually to push * to see all my inventory. It would be awesome if I'll be able to see whole inventory right after I pushed 'd' key!

This affects all item-operation commands, like d, k, w, t, E, F & etc

**Comment by b314** [comment]
This would have to be an option. I routinely pick up and destroy things while in battle and would hate to have my view of the main window blocked by my inventory.

**Comment by grking** [comment]
I was assuming only if you don't have a separate inventory term already open... or don't you have that either Warrior?

**Comment by b314** [comment]
I wouldn't want it even if I didn't have the inventory in another window, just too risky, in my opinion. Often the player will have a pretty much fixed inventory with just a few dynamic items and will know exactly the letter of what item he wants to do something with, without a list.

**Comment by igroglaz** [comment]
I play with 2 windows - game and messages, so operation with items at the moment is pretty torture because of this list.
