### ISSUE TITLE
Add an option to show chat messages in [Mirror window]

### ISSUE THREAD

**Issue by igroglaz** [mangband/mangband#1147]
If player using two main windows (main and mirror) - it's not possible to see in-game messages from other players. It would be fun to have an option to show _all_ messages in [Mirror window] ;)

**Comment by grking** [comment]
Don't use the Windows term4 hack if term 4 isn't active.

**Comment by igroglaz** [comment]
"Don't use the Windows term4 hack if term 4 isn't active." - sorry, I don't understand. I do not use any hacks (and donno what is 'hack' :))

**Comment by grking** [comment]
That wasn't aimed at you. That is an internal comment, translating your request into the required development change.

**Comment by billsey** [comment]
Term4 hack is the"creative" way messaging was handled in the Windows version. It's never been replaced with anything more standard.

Bill

Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by flambard-took** [comment]
Looks like I misunderstood / undertested this on Windows, it still doesn't do what @igroglaz wants.

**Comment by flambard-took** [comment]
Turns out, you can't rely on `ang_term[window_id] == NULL` test on WIN client, as it doesn't actually kill terminals, it only hides/shows them internally.
