### ISSUE TITLE
Idle timeout auto kick player if in dungeon

### ISSUE THREAD

**Issue by RaibowFairys** [mangband/mangband#1156]
Cuz die in dungeon when afk from hungry status.

Not bad if its will show like status in hud. For example red text "**AFK**".

**Comment by RaibowFairy** [comment]
i died few times cuz got weak status cuz was afk, and yes i quit game, and got weak status too. 1.1.3 ver

**Comment by RaibowFairy** [comment]
when you at work, have little brake and got weak status, then dead cuz afk its hurt realy.

**Comment by grking** [comment]
If a player is afk in the dungeon or wilderness, i.e. no actions taken, can we disconnect them after say 5 minutes? Or perhaps easier to express as a specific number of turns?

**Comment by billsey** [comment]
Number of turns is likely better, so we can still implement bubble time in the future.

**Comment by RaibowFairys** [comment]
Its a real time game, so disconect after 5 minutes mb will help.

**Comment by flambard-took** [comment]
Let's recap:
1. Some players **do want** auto-kick on starvation, but don't get it, leading to deaths.
2. Some players **do not** want auto-kick on starvation, yet they do get it (worst case scenario: you drink a potion of salt water, and that *immediately* kicks you out), leading to deaths.

Those are actually 2 symptoms of the same problem: the condition which triggers auto-kick is very brittle, and the check is performed at the wrong time. As it is now, the test is only performed **once**, when you first enter the "Weak" state, and it tests if you have full hp.

The full hp thing is completely random! Sometimes you might have full hp, sometimes don't... You have to be *extremely lucky* to hit all those conditions and them working in your favor, and not the other way around.

AFAIK, PowerWyrm made this a config option (`disturb_faint`), but I believe simply fixing the issue, and forcing it make sense will satisfy all concerned parties.

So, based on the discussion in this ticket, I'm going with a very simple fix:

- When player is BOTH starving AND is afk for 3 minutes, disconnect him.

**Comment by flambard-took** [comment]
eb9217b contains a bug, if a player reconnects very quickly (with his character still in the dungeon), the `afk_seconds` will keep the old value, and disconnect him once again.
