### ISSUE TITLE
Display the level of a character that died in the server death announcement 

### ISSUE THREAD

**Issue by RaibowFairy** [mangband/mangband#1159]
Add lvl text when char dead in message window.

**Comment by grking** [comment]
Can't quite understand what you mean...

**Comment by RaibowFairy** [comment]
http://prntscr.com/lonfr1 screenshote how it look in tomenet

**Comment by grking** [comment]
Yeah I agree that's a nice to have. I often wonder what level a character that just died was, let's add it.

**Comment by grking** [comment]
"Jug the level 29 Dwarf Warrior was killed by a mushroom patch"

**Comment by RaibowFairy** [comment]
cool, now you understand  what i mean xD
