### ISSUE TITLE
Win32 client: Rows increasing every time in [Mirror window] 

### ISSUE THREAD

**Issue by igroglaz** [mangband/mangband#1172]
I'm trying to assign in mangclient.ini:
NumRows=7
in [Mirror window] 

But after every restart, it's make it +1

I fixed it by making 'mangclient.ini' file 'only for reading' (in Windows 7 file properties), so it's a minor bug.. but still, wanna report it :)

**Comment by flambard-took** [comment]
I think it works as expected in develop, I was able to set `Rows=7` for `[Mirror window]` and it stayed the same after several client restarts. @igroglaz, please reopen if you're still having problem on 1.5.0.
