### ISSUE TITLE
"You have no spikes" when using inventory item "j"

### ISSUE THREAD

**Issue by RaibowFairys** [mangband/mangband#1174]
When using rods, staffs or wands. Sometimes got text "you have not spikes" and item not activated.

**Comment by grking** [comment]
Likely you are accidentally pressing "j".  Which is "spike a door command".

**Comment by RaibowFairys** [comment]
rod on "j" letter macros, but i use this as macros. \ez*1 so its not pressed by me as j

**Comment by igroglaz** [comment]
try to revise you macroses in .prf file; maybe one of them using 'j' key?

**Comment by RaibowFairys** [comment]
I not use "j" for macros xD its a letter that autopressed as bug i gues, cuz when in inventory letter is "j" its sometimes autopressed as bug. I use "*", for scrolls, now its a rod recall and sometimes apear too.

**Comment by igroglaz** [comment]
check this file: 'user-win.prf' in MAngband\lib\user for any 'j' in it :)

**Comment by RaibowFairys** [comment]
I not press j, just inventory count item is on "J" letter when used by rod or scroll by macros.
That why this is look strange.
