### ISSUE TITLE
Add autoload player config by default when start game.

### ISSUE THREAD

**Issue by RaibowFairys** [mangband/mangband#1177]
I suggest add autoload player config when player join game. Cuz always do at start shift+5 and load config not fun.

**Comment by grking** [comment]
As igroglaz mentions, the game looks for specific file names to automatically load.  I think the list of filenames used needs to be documented somewhere more obvious..

**Comment by billsey** [comment]
Player preferences should already load if named correctly. IIRC the global prefs load first then the race then class then player. Each can override the previous.

Bill

Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by flambard-took** [comment]
I hate to repeat what has already been said, but I'm thinking this needs some examples:

if I play a hobbit ranger, named Flambard, the following pref files will be loaded automatically:
```
hobbit.prf
ranger.prf
Flambard.prf
```

Also, closing this.
