### ISSUE TITLE
Rare chance of 'cure light/serious wounds' potions appearing in 4

### ISSUE THREAD

**Issue by igroglaz** [mangband/mangband#1179]
It seems it's quite rare to see cure light/serious wounds in temple (4) and it's not really make sense, as they should be more common then 'healing'. As you die pretty often in MAngband and restart a lot, it would be fun to find there some of minor potions more often. Or yet another approach - maybe there could be added small sub-shop (like a '+') at the same building with various cure light/serious/critical wounds potions? It wont hurt game balance, just would give possibility to wait for potions a bit less time.

**Comment by flambard-took** [comment]
This is a direct result of #1150 / 14a9a1d8.

I propose a new scheme:
```
{ TV_SCROLL, SV_SCROLL_LIFE	},
{ TV_POTION, SV_POTION_CURE_LIGHT },
{ TV_POTION, SV_POTION_CURE_SERIOUS },
{ TV_POTION, SV_POTION_CURE_CRITICAL },
{ TV_POTION, SV_POTION_HEALING },
{ TV_POTION, SV_POTION_RESTORE_EXP },
```

This way there is still a (slimmer) chance to find healing potions, yet low-level players retain access to cure light/serious wounds potions.
