### ISSUE TITLE
Add possibility to macro not only @-inscribed items, but also by items' names

### ISSUE THREAD

**Issue by igroglaz** [mangband/mangband#1182]
Currently players have to inscribe items again and again at every death to be able to use them via macroses. EX: I got a new char and bought 'phase door scrolls'. Now to use it with my macro \er9 I have to inscribe it with '@r9'. The same goes with all items.

It would be really great to be able to indicate not only @-inscriptions, but actully item names in macroses. EX: to make macro \erPhase to read 'phase door scroll'. 

It's one of the most important thing to implement imho.

Another approach to solve this problem is to create 'auto-inscriptions' engine (TomeNET got it), so all items which you have got auto-inscribed. I'll create separate issue about it.

**Comment by RaibowFairys** [comment]
not bad suggestion

**Comment by igroglaz** [comment]
This is the most urgent issue so far.

**Comment by igroglaz** [comment]
Why is it very important:

There is a problem:
every time when you die and start a new character - you have to inscribe manually all items again - all scrolls, potions & etc. And you die quite often in PWMA. And it's very annoying to reinscribe items after each death. 

So there could be two possible solution:

1) allow to macro with name of the item, like @Phase (right now you should use @r1 for it). Then after you saved macroses once - you don't need to bother about inscribing items again
2) auto-iscription feature (https://www.tomenet.eu/guide.php?chapter=0.3a)

I would prefer first variant, it's more comfortable.

**Comment by flambard-took** [comment]
a0cd88c3a150f8b16c925b3d821d3e5972db4af3 adds this functionality.

Note: you can use the `|` (pipe) symbol as generic "or", so you can combine item names and item flavors. (Example: `\q@healing|Azure`)

Note: book-by-spellname matcher from tomenet is **not** implemented, for no particular reason.

Note: as with tomenet, the matcher is case-insensitive, so both "phase" and "Phase" shall work.

Final note: I'm really loving this feature! And am going to use it extensively even for un-macroed commands, for example, now you can press "w" and type "@torch" without even glancing on your inventory screen. For people used to play MUDs, this should feel very natural. Thank you and thanks, tomenet!

**Comment by igroglaz** [comment]
YAY :1st_place_medal:
