### ISSUE TITLE
Higher resolution icon

### ISSUE THREAD

**Issue by flambard-took** [mangband/mangband#1197]
The 32x32 pixel icon looks blurry on modern, high-resolution desktops.

We need to remaster it to 4k :)

**Comment by billsey** [comment]
We probably ought to redo them in SVG so they are scalable. Of course that likely means a lot of work on the client. :)

Bill

Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by flambard-took** [comment]
Nope, no client changes necessary! OSX and WIN use bitmap icons (you just need to package 32x32, 64x64, 128x128, ..., 1024x1024 images into their respective .ico/.icns formats). The process (usually) is to manually export the SVG into all those images, so, yeah, if someone could please redo the icon in SVG format, that would be extremely sweet!

(If it ever comes to that, please note: the classic 32x32 version we use should be kept the same, as it's perfect pixel art, which no SVG scaling algorithm could replicate. Err, nevermind all that, just give me the SVG and I'll generate/commit proper .ico/.icns files)
