### ISSUE TITLE
Delete wilderness-hold.c

### ISSUE THREAD

**Issue by flambard-took** [mangband/mangband#1212]
This file is a leftover from times MAngband was not using *any* source control.

If I remember correctly this is either Crimon's updates over APD's code, either something very similar.

As far as I can tell (`diff -b -U3 wilderness.c wilderness-hold.c`), we already have every feature from it in our actual codebase, and there's no new/interesting code in it.

I propose we simply nuke it from the repo.

**Comment by billsey** [comment]
I concur. As far as I can see pretty much everything has been implemented in the current wilderness.c file.
