### ISSUE TITLE
Monsters are about 2.5 times faster compared to 1.4.1

### ISSUE THREAD

**Issue by flambard-took** [mangband/mangband#1248]
> [Zal] Does bubble-time make you skip a turn?
> [flambard] I don't think so
> [Zal] Ok. To me it seems like as soon as I enter bubble-time, the mob gets to react first every single time, which is weird, considering the mob just acted to get me to low health. I'm not sure though, as bubble-time still puts me off when it activates.

Not sure if it's really happening or just a perception thing, but we have to test, as I trust Zal's instincts.

**Comment by flambard-took** [comment]
I've tested this a lot and I can't reproduce it (at least, fighting a monster one-on-one). If I have 
maximum energy, and monster hits me (losing its energy), I always hit it back first.

So I'm thinking there must be some other condition that triggers this bug.

(If you're interesting in debugging timing issues, see `develop-timing` branch, which has a useful energy/commands queued indicator).

**Comment by flambard-took** [comment]
Grayshoe's explanation gave me another angle to examine this,
>yea, creatures are far for active , rarely ever remain sleeping and they are faster. all the orcs are faster than I am at normal speed above 500 feet
if im moving from away from any of the o's they can hit me at least every other turn

And so I checked: indeed monsters that *move at normal speed*, can hit you every turn, and so does a Speed: 110 (Normal +0) character. So, everything looks fine, except...

...in classic MAngband, monsters spent twice the energy after moving! It worked by giving them *negative energy*. For example, level speed is 45, monster starts with 0 energy. Over the course of 10 turns, he obtains 45 energy, which is enough to move. After moving, he spends energy once, getting 0, and then again, getting -45. Then, it takes *twice as long* to go from -45 to 45, so **players essentially are twice as fast as monsters, in classic MAngband**.

This is weird and wrong, but I'm going to restore this behavior :( It got smoked after time-bubbles/energy updates, and `monster_type.energy` now being a `u32b` (instead of something signed).

**Comment by flambard-took** [comment]
In addition, classic MAngband allowed players to "build-up" energy, meaning if they stayed still, for a while, they would get 2x level_speed(), allowing 2 consecutive turns to happen when a fight starts (giving players a bit of an upper-hand/initiative bonus).

**Comment by flambard-took** [comment]
So I don't know what to do, on one hand I *really like* the "no energy hacks and we're very close to how V works" situation, but on the other hand, we made the game about 2.5 times harder.

As a compromise I'm going to re-introduce both those behaviors as birth options, but I kinda think it's a terrible idea. Someone should just make a ruling one way or another and just flip the switch permanently.

**Comment by billsey** [comment]
Because of the real time element that is in Mangband that is not in vanilla it makes sense to have a movement penalty for monsters. In vanilla it's possible to have perfect player movement, where each game play movement can match a monster move. In Mangband it's nearly impossible to get that. I vote for a monster penalty similar to what we've had in the past.

Bill

Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by flambard-took** [comment]
@billsey, thank you! I'll also dump some comments by PowerWyrm:
>I'm pretty sure the monster spending energy twice was a bug, if monsters now act twice faster that means there's a second bug somewhere and the two were simply cancelling each other in old MAngband -- I'm using normal energy in PWMAngband and monsters act once per player turn, there is no such behavior as the one mentioned post 1.5 -- so it would be better to find the problem instead of adding some workaround (and as birth option lol)

(My comment: there isn't any problem, the situation indeed is as described) 

PowerWyrm concludes:
>having 1 bpr and dealing 2 should not be
>I'll check again when I have time, but I'm sure last time I checked I had no trouble with 1.5
