### ISSUE TITLE
Restore command macros (for now)

### ISSUE THREAD

**Issue by flambard-took** [mangband/mangband#1296]
Our code still *kinda* supports command macros (macro that only execute when the game is waiting for a command). We don't have a way to define them (not via the game ui, not via the pref file), though, and that's slight oversight.

Note: V has made a push to replace 'command macros' with keymaps, and indeed, keymaps can replace those, but command macros have some nice properties, that our keymap interface doesn't: they can be binded to any key + modifiers (keymaps are currently limited to single key, shift+key, ctrl+key, same as 'angband command').

**Comment by igroglaz** [comment]
command macroes help to rebind actions easely and also gives possibility to operate inventory. eg:
I bound '/' as phase door as normal macro. Now I want to read scroll of enhancement armour.. I read it and it shows my inventory. I want to switch view to equipment to enhance armour which I wear. But when I push '\' to switch it - it reads phase door :D

having command macro solve this (and a lot of other issues). if phase door is command macro - it wouldn't work when I got a promt in inventory :+1:
