### ISSUE TITLE
turn off auto-kick on fainting

### ISSUE THREAD

**Issue by igroglaz** [mangband/mangband#1325]
Today I've drinked potion and was kicked from the game

When I relogged I saw that char is starving, so it seems it was salt water potion.

Please could you add option not to kick player on starving, like Powerwyrm added recently:
http://angband.oook.cz/forum/showthread.php?p=135707&highlight=starving+kick#post135707

**Comment by flambard-took** [comment]
Duplicate of #1156.

**Comment by igroglaz** [comment]
Actually it's not duplicate, as it's vice versa issue. I saw that topic before I've created this one

**Comment by flambard-took** [comment]
You are somewhat right, but #1156 is actually another symptom of the same problem (auto-kick being broken, in multiple ways).
