### ISSUE TITLE
Hitpoint warning toggle hotkey

### ISSUE THREAD

**Issue by igroglaz** [mangband/mangband#1326]
It would be great to have possibility to turn on/off 'Hitpoint warning' mode by hotkey. Eg
player was attacked and got his HP to 50%.. 'HP warning' mode become triggered and time become slowed. Now if he want to have regular speed - he could push a hotkey (eg F1) to put time to normal speed... But if he wish to turn 'hp warning' mode on again - he could push this hotkey again.

**Comment by flambard-took** [comment]
Great idea, and should be easy to implement too.

Another, similar, suggestion by Zal, was to add a 100% threshold toggle, so that low-level mages could enable it at will.

**Comment by flambard-took** [comment]
Some info:

to set 100% threshold, use the `=` key on the `0-9` prompt.
to toggle current threshold, use the `-` key on the `0-9` prompt.

To macro those:

`\e=H0\e\e` - disable time bubbles
`\e=H5\e\e` - set threshold to 50% hp
`\e=H-\e\e` - toggle between 0 and your setting

First two options require 2 keys, but last option allows you to use a single(!) key.
