### ISSUE TITLE
Mouse controls

### ISSUE THREAD

**Issue by igroglaz** [mangband/mangband#1327]
> [15:49] flambard: BTW, depending on the client you use, Ctrl+Click should allow digging and Shift+Click should allow going downstairs, picking up items, etc.

is it possible to make LMB to move to certain point, RMB to interact (go downstart, pickup item, etc)?  actually it would be awesome to be able to bind more action on other buttons, eg I got additional rear buttons at my mouse.. If there would be possiblity to add there Phase door scroll and shooing - it would be quite possible to play as warrior by mouse..

I suppose I could assign such actions by side software (macro soft like Auto Hot Key), but if it's not to hard to implement, it would be fun to have it as native thing :)

**Comment by flambard-took** [comment]
Already doable, via manual pref file editing. Will eventually make it's way to the game ui.

Basically, edit `user.prf` and uncomment `mouse.prf`, so that it gets included.
Now edit `mouse.prf`, it contains some example.
