### ISSUE TITLE
Add Tangar's 1-bit font

### ISSUE THREAD

**Issue by flambard-took** [mangband/mangband#1372]
Long time coming, we should support Tangar's 1-bit font out of the box.

Since I *personally* don't like the squashed/stretched sizes of that font, I'm going to only include the proper 21x31 version to our client distribution.

However, the mappings will work for all the font sizes, so Players are free to add additional fonts. (**Once they are complete**)

As far as mappings go, I can't make them :( Sorry, it's just too hard of a task for me, even with scripting tools. Patches welcome.

**Comment by igroglaz** [comment]
I'll map it when will finish with Tangaria update ;)
