### ISSUE TITLE
strnfmt fails for 64 bit values if the format is "%llu"

### ISSUE THREAD

**Issue by jimevt** [mangband/mangband#1377]
Hi!
   Just trying to compile mangband for the first time.  I'm on Raspberry Pi Zero running Raspbian:'

       pi@gamepi: (544)> uname -a
       Linux gamepi 4.19.97+ #1294 Thu Jan 30 13:10:54 GMT 2020 armv6l GNU/Linux

   It appears to compile with no issues, but when I try to run it the perform_sanity_check() subroutine reports an error:

       290320 142459 strnfmt/sscanf mismatch for u64b llu/llu

   I added some debug code to try to figure out what was going on:

	sprintf(buf, "%" PRIu64, tmp64u);
	sscanf(buf, "%" SCNu64, &_tmp64u);
	printf("---JAE - tmp64u=%llu\n", tmp64u);
	printf("---JAE - buf=%s\n", buf);
	printf("---JAE - _tmp64u=%llu\n", _tmp64u);
	printf("---JAE - PRIu64=%s\n", PRIu64);
	printf("---JAE - PRIu64=%s\n", PRIu64);
	printf("---JAE - SCNu64=%s\n", SCNu64);
	if (tmp64u != _tmp64u) quit_fmt("printf/sscanf mismatch for u64b %s/%s", PRIu64, SCNu64);

	strnfmt(buf, sizeof(buf), "%" PRIu64, tmp64u);
	_tmp64u = 0;
	sscanf(buf, "%" SCNu64, &_tmp64u);
	printf("---JAE(2) - tmp64u=%llu\n", tmp64u);
	printf("---JAE(2) - buf=%s\n", buf);
	printf("---JAE(2) - _tmp64u=%llu\n", _tmp64u);
	printf("---JAE(2) - PRIu64=%s\n", PRIu64);
	printf("---JAE(2) - PRIu64=%s\n", PRIu64);
	printf("---JAE(2) - SCNu64=%s\n", SCNu64);
	if (tmp64u != _tmp64u) quit_fmt("strnfmt/sscanf mismatch for u64b %s/%s", PRIu64, SCNu64);

   And here is the output:

./mangband 
---JAE - tmp64u=17868022691004938231
---JAE - buf=17868022691004938231
---JAE - _tmp64u=17868022691004938231
---JAE - PRIu64=llu
---JAE - PRIu64=llu
---JAE - SCNu64=llu
---JAE(2) - tmp64u=17868022691004938231
---JAE(2) - buf=13731520863385679863
---JAE(2) - _tmp64u=13731520863385679863
---JAE(2) - PRIu64=llu
---JAE(2) - PRIu64=llu
---JAE(2) - SCNu64=llu
290320 142459 strnfmt/sscanf mismatch for u64b llu/llu

It looks like it is correctly using "%llu" for an "unsigned long long", sprintf/sscanf work correctly, but the manband subroutine strnfmt() doesn't seem to handle the "%llu" correctly.

I looked in z-form.c and found that strnfmt() calls vstrnfmt(), and that subroutine only sets the "do_long_long" flag to TRUE in cases where the format has an "I" in it, as in "I64" - one of the possible formats for other platforms.

   Is somebody an expert at this code?  Or should I try to hack together a solution?  :-)

JimE.

**Comment by jimevt** [comment]
Hmmm.... This might have fixed it... in z-form.c:				

				/* Hack -- handle "long" request */
				else if (*s == 'l')
				{
					/* Save the character */
					aux[q++] = *s++;

					/* Note the "long" flag */
					if ( TRUE == do_long  ) {
					  do_long = FALSE;
					  do_long_long = TRUE;
					} else {
					  do_long = TRUE;
					}
				}

				/* Mega-Hack -- handle "extra-long" request */

**Comment by flambard-took** [comment]
@jimevt ,
1. thank you very much for bravely diving into this issue
2. no, nobody is an expert in this code, see #1349 
3. your modification appears correct, but I'll need to check it on each and every supported platform :(

this will take a few days, but rest assured, will be eventually applied, because fixing #1349 is of great importance to us.
