### ISSUE TITLE
FreeBSD build: compile fixes

### ISSUE THREAD

**Issue by adriaandegroot** [mangband/mangband#1395]
The FreeBSD package of mangband **was** 1.1.3, and I'm updating it to 1.5.3 now. There are some patches we've carried for years (w/ 1.1.3) and some new ones which are needed because clang / llvm are getting quite picky about things: duplicate symbols in particular.

**Comment by adriaandegroot** [comment]
In the `VERIFY_SAVEFILE` case, there's a `strcpy()` that needs fixing. Maybe it's weird to have this option set for mangband, but we've carried it for a long time.

[patch-server.txt](https://github.com/mangband/mangband/files/6006265/patch-server.txt)

**Comment by adriaandegroot** [comment]
There are multiple definitions of some user info variables: `player_uid` and `player-egid` are defined in `src/server/variable.c` and in `src/common/z-file.c`, while `player_euid` is defined but never used.

I've kind-of-arbitrarily kept the definitions in common, and removed them from server -- that's kind of ass-backwards compared to `z-file.h` now that I look at it more closely.

[patch-common.txt](https://github.com/mangband/mangband/files/6006320/patch-common.txt)
[patch-variable.txt](https://github.com/mangband/mangband/files/6006321/patch-variable.txt)

**Comment by adriaandegroot** [comment]
(I can PR this if you like, that is easier than reading patches in comments)

**Comment by flambard-took** [comment]
@adriaandegroot terribly sorry for the late reply, I'm extremely happy to see an update for the FreeBSD port! I'll mention this on the main website ASAP (as 1.1.3 is a terribly old version).

I also remember there were some problems with 1.1.X build system, which made packaging harder, I don't remember the particulars, but I believe we now have a fully complaint automake/autoconf process (with all the --path-flags working correctly), no longer require GNU make (BSD make should work fine), and probably something else related. But I've taken a look at the latest file in the ports collection, and everything looks pretty good already, so you've probably taken care of all those things :)

In any case, thank you very much for the update, and yeah, a PR with the patches would be most welcome. (But if you don't have any extra time to spend on this, it's all good anyway, I'll use attached `.txt`s).

**Comment by adriaandegroot** [comment]
The four patches we now carry in packaging -- I've had no complaints about mangband, but frankly I have no idea how many people play it on FreeBSD -- can all be found [here](https://github.com/freebsd/freebsd-ports-kde/tree/master/games/mangband/files) as well. Packaging looks straightforward now.
