### ISSUE TITLE
mangband.org is down. List of community servers to play

### ISSUE THREAD

**Issue by igroglaz** [mangband/mangband#1397]
Official website and metaserver down, so for now to play MAngband you can directly connect to these servers:
1) **mangband.arfonzo.org**
Version: 1.1.3
2) **mangband.passiverpg.com**
Version: 1.5.3
3) **ironman.seymourfamily.com**
Version: 1.5.0 Ironman development

also to play PWMAngband:
**pwmangband.seymourfamily.com**
Version: 1.4.0 (Build 4)

**To download client/server:
https://github.com/mangband/mangband/releases**

@flambard-took @grking @billsey @driedfruit @VectorShadow @Thorbear @emlai  FOLKS. It's unknown why MAngband.org is down. @evileye-uk pinged everyone in discord, but for now there are no news. If anyone knows whats happened to mangband.org - please tell us. Mangband.org domain expiry date: 2021-11-04T16:13:26Z

**Comment by grking** [comment]
The server had been shutdown, no clue, not me. It's been started up again.

**Comment by grking** [comment]
Although the meta server hasn't been started. Can't remember where that is :)

**Comment by grking** [comment]
OK, I've started *a* meta server. Not sure if it's _the_ meta server. Seems to work.

**Comment by igroglaz** [comment]
@grking meta is down
![image](https://user-images.githubusercontent.com/39904162/190117697-6496bbd5-f919-49e3-aca1-a21431c10d25.png)

**Comment by igroglaz** [comment]
@grking 
![image](https://github.com/mangband/mangband/assets/39904162/f65645e2-fc67-466e-b4db-97a97a8851f8)
