### ISSUE TITLE
Gold drop disconnects client

### ISSUE THREAD

**Issue by mangband** [mangband/mangband#417]
Issue raised by flambard

1. Unknown packet still crashes server when delayed BUT only if it's different from the packet originally recieved.. But how is that possible?
2. It is possible in one extremley rare case of gold drop because of typo in the delaying code.

**Comment by evileye-uk** [comment]
Pointer is to s32b for amt. the Packet_scanf overwrites value of player when long is 64 bit.

**Comment by evileye-uk** [comment]
All to do with 64-bit vs 32-bit long. Overwriting player (the earlier variable in list) causes it to be 0. That will mean p_ptr ends up being a null pointer, etc..
