### ISSUE TITLE
Invisible Monsters can affect running.

### ISSUE THREAD

**Issue by mangband** [mangband/mangband#534]
Issue raised by kismet

Obviously, this is a dead give-away.  If a monster is not visible to the player, you should be able to run normally.  Caveat here, I'm not sure you should be able to run after it's obvious _something_ is there, such as if it hit you.

**Comment by flambard-took** [comment]
I've given this an extensive testing, and with new running system, we don't have this bug.

In fact, we have the inverse problem: invisible monster, that is in LOS, and is detected by magical means (telepathy) doesn't count as a "dangerous" monster, and players can run past them.
