### ISSUE TITLE
Artifacts should not be found multiple times

### ISSUE THREAD

**Issue by mangband** [mangband/mangband#541]
Issue raised by jug

Players repeatedly find the same artifacts over and over again.  One proposed solution is the artifacts sold to the shop should never be found again. Artifacts left in the dungeon should be available to find again in the future.

This will remove the both the annoyance of finding the same crappy arts over and over again and also the cheezyness of making huge amounts of cash from selling the same item.

**Comment by flambard-took** [comment]
Note: artifact highlighting is *still* incorrect
