### ISSUE TITLE
Re-enable graphics

### ISSUE THREAD

**Issue by mangband** [mangband/mangband#606]
Issue raised by flambard

Some time ago we had them, now we don't.

**Comment by flambard-took** [comment]
I'm seeing _objflags-related packet parsing errors again. Might be bug in rle encoding/decoding, might be the same issue as before (although it doesn't look like it).

**Comment by flambard-took** [comment]
Also, [3b8818b69757921edc93b844110e289692f94058]

**Comment by flambard-took** [comment]
As far as ticket mission statement goes, it's done.
