### ISSUE TITLE
Better item_tester handling

### ISSUE THREAD

**Issue by mangband** [mangband/mangband#807]
Issue raised by powerwyrm

The main method when asking the player to choose an item from equipment, pack or floor uses a check against tval (item_tester_tval) and a "hook" method for more precise item selection (item_tester_hook). Currently this system is really poorly implemented:

Client side:
- c_get_item: item_tester_tval and item_tester_hook are almost never implemented, letting the player choose anything (see cmd_refill for example...)
- Receive_item: item_tester_tval and item_tester_hook are not implemented, the player can choose anything (when enchanting, branding...)

Server side:
- get_item: item_tester_tval and item_tester_hook are defined, but the code doesn't reference them anywhere
- Send_item_request: calls the client asking to choose an item without any restriction
- items failing to satisfy the requirements generate useless messages (you cannot enchant this, you cannot recharge that...)

A much better solution would be to implement this:
- c_get_item: implement item_tester_tval and/or item_tester_hook each time this function is called to restrict object choices to valid objects
- item_tester_hook: implement on the client the hooks coded on the server (item_tester_hook_ammo, item_tester_hook_recharge...); this will require expanding the info sent by the server to the client when refreshing inventory and floor (sval, ...)
- Receive_item: item_tester_tval and item_tester_hook should be received from the server and implemented to restrict object choices to valid objects
- get_item: remove item_tester_tval and item_tester_hook from the server code; use direct checks instead
- Send_item_request: the tval to test and/or the tester hook to call should be sent to the client
- items failing to satisfy the requirements on the server should not generate messages, but let the function fail silently (similar to the changes applied in #677); this case should almost never happen, since the client should have selected a valid item

**Comment by flambard-took** [comment]
As explained by PowerWyrm, we still lack finesse when selecting certain items.

Note, that *primary* item testers are already implemented and work rather well, e.g. "read scroll" command only allow selection of scroll items.

However, sometimes we need *secondary* item testers, when a spell or effect requires a secondary item to work (e.g. scroll of enchant weapon, should only allow selection of weapons, unless it's effects are not known to the player).

As mentioned, this requires expansion of the data sent from the server to the client, in particular, mage/priest spells, but also for inventory items, like staves and scrolls.
