### ISSUE TITLE
format() produces garbled text

### ISSUE THREAD

**Issue by mangband** [mangband/mangband#854]
Issue raised by powerwyrm

As the description of the method says, "Do a vstrnfmt() into a (growable) static buffer. This buffer is usable for very short term formatting of results."

However, this function is used in cases where the returned string is used much later than the moment it is allocated. In this cases, the format buffer can be erased and the returned string is no longer valid when it is used, leading to garbled text being prompted. A good example of this is the use of format() to get the "reason" parameter to the Destroy_connection() function.

In an ideal world, format() should never be used, and the more robust strnfmt() should be used instead.

**Comment by evileye-uk** [comment]
Have converted this and deleted format and associated functions that use the static buffer. Just going through checks.

**Comment by flambard-took** [comment]
In (e58f2fb550a9f79da1235ba855e54ae59f46360e) Use array of buffers in format(), allow up to 5 consecutive calls. See #854
