### ISSUE TITLE
Reimplement sound

### ISSUE THREAD

**Issue by mangband** [mangband/mangband#858]
Issue raised by flambard

I'm not sure about the status of our sound framework, but we should bring it up to date, make it compatibale with V and ensure all terminals that could - do support it.

**Comment by flambard-took** [comment]
PW, do you still have the sound patch hosted anywhere?

Also, confirming WIN portion still works.

**Comment by flambard-took** [comment]
> The static methods init_sound() and cleanup_sound() don't seem to be called anywhere in 2925477...

good catch by PW, as always. Note: cleanup_sound IS STILL not being called from anywhere.

**Comment by flambard-took** [comment]
Since c7c875e4878bdc92b6f6301299e160eaf664d5dd, `cleanup_sound` is called from `quit_sdl`. That was the last issue with this ticket.
