### ISSUE TITLE
Destroy staves/wands on recharge again

### ISSUE THREAD

**Issue by mangband** [mangband/mangband#876]
Issue raised by flambard

Since #206, r243, "wands and staves are not destroyed on failure".

As this change was reverted from latest Angband and magic devices become even more convinient with stacking, it was decided unlimited recharging should go away.

We can keep it as an opt-in option.

**Comment by flambard-took** [comment]
All four fixes from V309, that were outlined by PowerWyrm are now applied.

**Comment by flambard-took** [comment]
Re-opening, because we shall apply fixes from later V, and because the rod situation is still questionable.
