### ISSUE TITLE
Interactive help

### ISSUE THREAD

**Issue by mangband** [mangband/mangband#891]
Issue raised by flambard

In Angband, player can browse through several help files interactivly. We shall re-enable this behavior.

**Comment by flambard-took** [comment]
First 3 problems should be resolved in it's own ticket -- #1040.

**Comment by flambard-took** [comment]
1de49f4 hackishly solves the buffer swapping issue, and this whole ticket was about interactive help, not about network terminals/streams, so I'm closing this.
