### ISSUE TITLE
Port V309 z-term

### ISSUE THREAD

**Issue by mangband** [mangband/mangband#944]
Issue raised by flambard

In V, the z-term code become much cleaner since we forked. We shall port it here and make required changes to the WIN, SDL, GCU and X11 clients.

**Comment by flambard-took** [comment]
There is a long-standing bug, Term_load and Term_save leak memory. Those functions are always to be called together, however Term_load doesn't free what Term_save allocates. This is already fixed in very latest versions of Angband.

**Comment by flambard-took** [comment]
Wait, this has been completed a long time ago.
