### ISSUE TITLE
Clients should never wait for a keypress without informing the server

### ISSUE THREAD

**Issue by mangband** [mangband/mangband#951]
Issue raised by powerwyrm

This happens when Term_inkey is called with wait = TRUE. In this case, clients don't send anything to the server and anything received from the server is blocked until a key is pressed. This is ok in turn based, not in real time. At best, you'll get a "Timeout 08" error, and the client will be disconnected. If you're unlucky, you'll find your character dead after a key is pressed.

Look at the code below:

```
/*
 * Loop, looking for net input and responding to keypresses.
 */
ui_event_data Net_loop(errr (*inkey_handler)(ui_event_data*, bool, bool),
    void (*callback_begin)(char*), void (*callback_end)(void))
{
    char ch;
    ui_event_data ke;
    int net_fd;

    /* Assume error */
    ke.type = EVT_ERROR;

    /* Acquire and save maximum file descriptor */
    net_fd = Net_fd();

    /* If no network yet, just wait for a keypress */
    if (net_fd == -1)
    {
        /* Look for a keypress */
        if (inkey_handler) inkey_handler(&ke, TRUE, TRUE);

        /* Report error */
        else plog("Bad socket file descriptor");

        return ke;
    }

    /* Wait for keypress, while also checking for net input */
    for (ch = 0; !ch; )
    {
        /* Look for a keypress */
        if (inkey_handler)
        {
            inkey_handler(&ke, FALSE, TRUE);
            ch = ke.key;
        }

        /* Call our callback */
        if (callback_begin) callback_begin(&ch);

        /* If we got a key, break */
        if (ch) break;

        /* Update our timer and if necessary send a keepalive packet */
        do_keepalive();

        /* Flush the network output buffer */
        if (Net_flush() == -1)
        {
            plog("Bad net flush");
            ke.type = EVT_ERROR;
            return ke;
        }

        /* Wait for .001 sec, or until there is net input */
        SetTimeout(0, 1000);

        /* Update the screen */
        Term_fresh();

        /* Parse net input if we got any */
        if (SocketReadable(net_fd))
        {
            if (Net_input() == -1)
            {
                ke.type = EVT_ERROR;
                return ke;
            }
        }

        /* Call our callback */
        if (callback_end) callback_end();

        /* Redraw */
        redraw_stuff();
    }

    return ke;
}
```

This is the code I use for my variant to handle events and keypresses (with the proper callbacks, it can be used to replace a lot of code: in Input_loop, do_cmd_store, inkey_aux, SDL_ScaleTiledBitmap...). This code could be used to replace calls to Term_inkey(&ke, TRUE, TRUE): just do ke = Net_loop(Term_inkey, NULL, NULL);

**Comment by flambard-took** [comment]
I really like that approach and almost went with the callback too, but then it dawned on me, that it's not the key/network problem, but entering new network loops from inside old ones actually is.

To wit:
```
network_loop:
    recv_something:
        do_something_interactive:
            inkey():
                network_loop
```

This will definitely end bad in the new networking code. The packets from the outer network_loop hasn't been parsed completely yet, and the queue state is still changing at this point.

In old netcode, this is *somewhat* mitigated by doing multiple checks and re-checks and re-re-checks from inside the inkey function. For new code, I propose we remove the possibility to enter this situation completely:
```
network_loop:
    recv_something:
        remember_to_do_something_interactive = TRUE
# later...
if remember_to_do_something_interactive is TRUE:
    do_something_interactive:
        inkey():
            network_loop
```

This way we will always have at most one layer of network loop running.
