### ISSUE TITLE
Indicators

### ISSUE THREAD

**Issue by mangband** [mangband/mangband#962]
Issue raised by flambard

Part of #952. Indicators are tiny bits of data shown to the player. "Cur HP", "Level" and "Depth" are all indicator examples.

**Comment by flambard-took** [comment]
Outstanding problems:
- [ ] Indicators are blue
- [ ] Charsheet Name indicator has extra colon
- [ ] Charsheet indicators are not duplicated
- [ ] Compact window is not displaying indicators
- [ ] Status window is not displaying indicators
- [ ] Race, Class indicators are not redrawn on Ctrl+R refresh
- [ ] Race, Class, Title indicators are of wrong color
- [ ] Gold/AU indicator is of wrong color
- [ ] Speed indicator has +9 debug modifier
- [ ] Cur HP indicator has -2 debug modifier
- [ ] Not using "old-school" HP/SP indicators
- [ ] Depth indicator (re-)appears on status window
- [ ] Compact Indicator area on main terminal is still sometimes dirty
- [ ] Compact window shows legacy indicators (shouldn't, expect for few)
- [ ] Charsheet shows legacy indicators (shouldn't, expect for few)
