### ISSUE TITLE
Looking while hallucinating will prevent walking

### ISSUE THREAD

**Issue by mangband** [mangband/mangband#966]
Issue raised by warrior

Attempting to look while hallucinating will prevent you from walking.

Eat a mushroom of hallucination > look > "You can't believe what you are seeing!" > enter any direction and you'll get the same message again. Hitting escape cancels the stuck "look" and will let you select and move into a direction again.

Also, it should not be possible to examine items while hallucinating. Arguably it should affect a few more things as well, such as shop interaction and item interaction in general (accessing items in the inventory could return a "Your potions have all turned into fuzzy ducks!" or a similarly weird message :)

**Comment by flambard-took** [comment]
Seems to be fixed somewhere during the course of #798.

The new behavior is still not ideal, but at least you don't get into weird semi-looking state without knowing it. Spinning-off the rest of suggestions into a new ticket #1193.
