### ISSUE TITLE
Teleport away in store doesn't quite teleport.

### ISSUE THREAD

**Issue by mangband** [mangband/mangband#982]
Issue raised by billsey

When a player is in a store and another player uses teleport away to get them out, the first player stays in the store, yet frees the store up for entry. When the first player leaves the store, they are placed elsewhere from the teleport. The player should either leave the store as part of the teleport or should stay in the store and the teleport should fail.

**Comment by flambard-took** [comment]
Looks like this is resolved in latest develop.
