### ISSUE TITLE
Port low-level file access from V

### ISSUE THREAD

**Issue by mangband** [mangband/mangband#990]
Issue raised by flambard

Currently, we use a dirty mix of my_fopen and fd_open APIs to read/write files. Sometimes we even call system fopen. In V, they first unified the API to my_fopen form (V306), then rewrote it to be more opaque (V312 the file_open ang_file* form). Another drawback is that the code is duplicated between client and server, while it should obviously be in libcommon.

I propose we just take the latest file_open routines and go with them (see z-file.c and z-file.h in V312). 

The added benefit is that they have also warped directory-reading routines, while we resort to testing IF_HAVE_DIRENT in-place. 
And it might help us porting binary save code later.

**Comment by flambard-took** [comment]
Continued in #1093.
