### ISSUE TITLE
Remove non-curses code from curses port

### ISSUE THREAD

**Issue by mangband** [mangband/mangband#991]
Issue raised by flambard

We have main-xaw and main-cap (and main-ibm? and others?) for various console-only ports. Those should work in shell without the need of curses library.

However, we also have some dirty workarounds to enable same functionality _inside_ the main-gcu client. This makes some sense, but is ultimately wrong -- those workarounds are largely for arcane systems depending on defines we don't use anymore.

I suggest we remove all non-curses code from the GCU client.

**Comment by flambard-took** [comment]
I believe this ticket was misguided, the weird termcap code in ncurses port might be helpful on some platforms.
